version: '3.9'

services:
  signup-db:
    image: docker4dotnet/sql-server:2017
    environment:
      - sa_password=docker4.net!
    networks:
      - signup-net

  signup-web:
    image: web-signup-imgv6
    ports:
      - 8881:80
    depends_on:
      - signup-db
    networks:
      - signup-net

  reference-data-api:
    image: ref-api-img:v2
    ports:
      - 8082:80
    depends_on:
      - signup-db
    networks:
      - signup-net

networks:
  signup-net:

