version: '3.9'

services:
  signup-web:
  image: sajidaz1994.azurecr.io/signup-web
    build:
      context: ./
      dockerfile: Dockerfilev6

  reference-data-api:
  image: sajidaz1994.azurecr.io/refer-data-api
    build:
      context: ./
      dockerfile: Docker-ref-api

